branch-defaults:
  spring:
    environment: null
deploy:
  artifact: build\libs\ga-rest-api-0.7.0.jar
global:
  application_name: genetic-algorithm
  branch: null
  default_ec2_keyname: aws-eb-key
  default_platform: Java 8
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
