# This work is based on the Gradle Docker file, see: https://github.com/keeganwitt/docker-gradle/blob/a206b4a26547df6d8b29d06dd706358e3801d4a9/jdk8/Dockerfile

#FROM adoptopenjdk:8-jdk-hotspot
FROM openjdk:8-alpine

RUN apk add --no-cache \
  --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ nodejs=8.9.3-r1
