-- INSERT INTO public.lecturers ("name", department_id) VALUES('LECTURER', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('A Brennan', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('A McCluskey', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('C Mulvihill', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('C ORiordan', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('D Chambers', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('D Flannery', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('D OSullivan', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('D Roshansangachin', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('E Barrett', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('E Curry', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('F Glavin', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('F Smith', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('G Ellis', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('H Melvin', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('H Vornhagen', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('H Yang', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('I Ullah', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Breslin', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Cruickshank', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Duggan', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Griffith', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Newell', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('J Burns', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('M Madden', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('M Nickles', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('M Schukat', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('M Tuite', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('N Madden', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('N Snigireva', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('O Molloy', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('R Quinlan', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('S Hill', 1);
-- INSERT INTO public.lecturers ("name", department_id) VALUES('S Redfern', 1);

INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(1, 'LECTURER', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(5, 'A Brennan', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(6, 'A McCluskey', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(7, 'C Mulvihill', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(8, 'C ORiordan', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(9, 'D Chambers', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(10, 'D Flannery', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(12, 'D Roshansangachin', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(13, 'E Barrett', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(14, 'E Barrett', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(16, 'E Curry', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(17, 'F Glavin', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(18, 'F Smith', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(19, 'G Ellis', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(20, 'H Melvin', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(21, 'H Vornhagen', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(22, 'H Yang', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(23, 'I Ullah', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(24, 'J Breslin', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(25, 'J Cruickshank', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(26, 'J Duggan', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(27, 'J Griffith', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(28, 'J Newell', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(29, 'J Burns', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(30, 'M Madden', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(31, 'M Nickles', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(32, 'M Schukat', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(33, 'M Tuite', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(34, 'N Madden', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(35, 'N Snigireva', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(36, 'O Molloy', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(37, 'R Quinlan', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(38, 'S Hill', 1);
INSERT INTO public.lecturers (lecturer_id, "name", department_id) VALUES(39, 'S Redfern', 1);
