INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(7, 'Advanced Professional Skills', 5, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(8, 'Algorithms', 7, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(9, 'Algorithms & Information Systems', 27, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(10, 'Algorithms and Logical Methods', 7, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(11, 'Applied Regression Models', 22, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(12, 'Artificial Intelligence', 7, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(13, 'Computer Architecture and Operating Systems', 32, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(14, 'Computer Systems', 18, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(15, 'Computer Systems & Organisation', 17, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(16, 'Computer Systems & Organisation Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(17, 'Computer Systems Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(18, 'Computing Systems', 17, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(19, 'Computing Systems Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(20, 'Database Systems I', 27, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(21, 'Database Systems I Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(22, 'Database Systems II', 8, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(23, 'Differential Forms', 19, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(24, 'Digital Signal Processing', 1, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(25, 'Discrete Mathematics', 34, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(26, 'Discrete Mathematics (H)', 34, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(27, 'Eculidean & Non-Euclidean Geometry', 29, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(28, 'Engineering Statistics', 28, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(29, 'Fundamentals of EEE', 24, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(30, 'Graphics & Image Processing', 39, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(31, 'Groups', 37, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(32, 'Human Computer Interaction', 21, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(33, 'Humanities Applications', 5, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(34, 'Internet Programming ', 13, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(35, 'Internet Programming Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(36, 'Intro to Natural Lang. Processing', 1, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(37, 'Intro to Natural Lang. Processing Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(38, 'Intro. To Statistical Data and Probability', 12, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(39, 'Machine Learning and Data Mining', 30, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(40, 'Mathematics', 25, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(41, 'Mathematics (H)', 19, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(42, 'Mathematics workshop', 29, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(43, 'Measure Theory', 35, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(44, 'Metric Spaces', 6, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(45, 'Modelling I', 1, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(46, 'Modern Information Management', 8, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(47, 'Network & Data Communications 2', 9, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(48, 'Network & Data Communications 2 Lab', 9, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(49, 'Next Generation Technologies l', 39, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(50, 'Next Generation Technologies ll', 32, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(51, 'Next Generation Technologies ll Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(52, 'Next Generation Technology III', 39, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(53, 'Next Generation Technology III Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(54, 'Numerical Analysis I (H)', 34, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(55, 'Object Oriented Programming', 38, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(56, 'Object Oriented Programming Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(57, 'Probability', 12, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(58, 'Professional Skills I', 13, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(59, 'Programming for Data Analytics ', 26, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(60, 'Programming for Data Analytics Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(61, 'Programming I', 36, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(62, 'Programming I Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(63, 'Programming III', 9, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(64, 'Programming III Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(65, 'Programming Paradigms', 18, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(66, 'Programming Paradigms Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(67, 'Research Project', 7, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(68, 'Rings', 10, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(69, 'Software Design & Development Project', 18, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(70, 'Software Engineering I', 13, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(71, 'Software Engineering I Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(72, 'Software Engineering II', 36, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(73, 'Software Engineering II Lab', 1, true);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(74, 'Software Engineering III', 32, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(75, 'Systems Modelling and Simulation', 26, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(76, 'Systems Modelling and Simulation Lab', 26, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(77, 'Tools & Techniques for Large Scale DA Lab', 31, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(78, 'Tools & Techniques for Large Scale Data Analytics ', 31, false);
INSERT INTO public.modules (module_id, "name", lecturer_id, is_lab) VALUES(79, 'Web Information Systems', 27, false);




-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Advanced Professional Skills',5,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Algorithms',7,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Algorithms & Information Systems',27,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Algorithms and Logical Methods',7,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Applied Regression Models',22,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Artificial Intelligence',7,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computer Architecture and Operating Systems',32,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computer Systems',18,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computer Systems & Organisation',17,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computer Systems & Organisation Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computer Systems Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computing Systems',17,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Computing Systems Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Database Systems I',27,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Database Systems I Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Database Systems II',8,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Differential Forms',19,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Digital Signal Processing',1,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Discrete Mathematics',34,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Discrete Mathematics (H)',34,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Eculidean & Non-Euclidean Geometry',29,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Engineering Statistics',28,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Fundamentals of EEE',24,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Graphics & Image Processing',39,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Groups',37,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Human Computer Interaction',21,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Humanities Applications',5,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Internet Programming ',13,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Internet Programming Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Intro to Natural Lang. Processing',1,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Intro to Natural Lang. Processing Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Intro. To Statistical Data and Probability',12,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Machine Learning and Data Mining',30,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Mathematics',25,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Mathematics (H)',19,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Mathematics workshop',29,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Measure Theory',35,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Metric Spaces',6,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Modelling I',1,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Modern Information Management',8,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Network & Data Communications 2',9,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Network & Data Communications 2 Lab',9,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Next Generation Technologies l',39,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Next Generation Technologies ll',32,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Next Generation Technologies ll Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Next Generation Technology III',39,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Next Generation Technology III Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Numerical Analysis I (H)',34,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Object Oriented Programming',38,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Object Oriented Programming Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Probability',12,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Professional Skills I',13,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming for Data Analytics ',26,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming for Data Analytics Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming I',36,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming I Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming III',9,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming III Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming Paradigms',18,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Programming Paradigms Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Research Project',7,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Rings',10,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Design & Development Project',18,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Engineering I',13,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Engineering I Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Engineering II',36,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Engineering II Lab',1,TRUE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Software Engineering III',32,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Systems Modelling and Simulation',26,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Systems Modelling and Simulation Lab',26,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Tools & Techniques for Large Scale DA Lab',31,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Tools & Techniques for Large Scale Data Analytics ',31,FALSE);
-- INSERT INTO public.modules ("name", lecturer_id, is_lab) VALUES('Web Information Systems',27,FALSE);
