INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(6, 'CA001', 6, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(7, 'CA002', 6, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(8, 'CA003', 6, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(9, 'CA004', 6, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(10, 'CA114', 6, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(11, 'CA115', 6, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(12, 'CA116a', 6, false, 60);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(13, 'CA117 (MBA Room)', 6, false, 48);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(14, 'CA118', 6, false, 60);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(15, 'CA111 (Lecture Hall 1)', 6, false, 105);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(16, 'CA101 (Lecture Hall 2)', 6, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(17, 'MY123', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(18, 'MY124', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(19, 'MY125', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(20, 'MY126', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(21, 'MY127', 8, false, 80);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(22, 'MY129', 8, false, 105);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(23, 'MY231', 8, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(24, 'MY232', 8, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(25, 'MY243', 8, false, 232);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(26, 'MY336', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(27, 'MY337', 8, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(28, 'AUC-G002 (Theatre Áras Ui Chathail)', 5, false, 166);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(29, 'AM104', 3, false, 34);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(30, 'AM105', 3, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(31, 'AM107', 3, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(32, 'AM108', 3, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(33, 'AM109', 3, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(34, 'AM110', 3, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(35, 'AM112', 3, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(36, 'AM121', 3, false, 12);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(37, 'AM122', 3, false, 12);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(38, 'OTnuathail Theatre', 3, false, 147);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(39, 'Fottrell Theatre', 3, false, 212);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(40, 'OhEocha Theatre', 3, false, 252);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(41, 'AMB-G036', 3, false, 45);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(42, 'AMB-G043', 3, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(43, 'BLE-1006', 9, false, 80);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(44, 'OFlaherty Theatre', 2, false, 356);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(45, 'Anderson Theatre', 2, false, 242);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(46, 'DArcy Thompson Theatre', 2, false, 160);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(47, 'AC201', 2, false, 97);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(48, 'AC202', 2, false, 88);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(49, 'AC203', 2, false, 48);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(50, 'AC204', 2, false, 48);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(51, 'AC213', 2, false, 70);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(52, 'AC214', 2, false, 56);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(53, 'AC215', 2, false, 70);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(54, 'AC216', 2, false, 70);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(55, 'Kirwan Theatre', 2, false, 312);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(56, 'Larmor Theatre', 2, false, 93);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(57, 'Dillon Theatre', 2, false, 95);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(58, 'McMunn Theatre', 2, false, 94);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(59, 'Tyndall Theatre', 2, false, 125);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(60, 'TB301', 10, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(61, 'TB302', 10, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(62, 'TB303', 10, false, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(63, 'TB304', 10, false, 19);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(64, 'TB305', 10, false, 19);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(65, 'TB307', 10, false, 22);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(66, 'ENG-G017', 4, false, 136);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(67, 'ENG-G018', 4, false, 246);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(68, 'ENG-G047', 4, false, 117);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(69, 'ENG-2001', 4, false, 74);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(70, 'ENG-2002', 4, false, 75);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(71, 'ENG-2003', 4, false, 52);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(72, 'ENG-2033', 4, false, 50);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(73, 'ENG-2034', 4, false, 50);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(74, 'ENG-2035', 4, false, 50);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(75, 'ENG-3035', 4, false, 74);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(76, 'ENG-3036', 4, false, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(77, 'IT101 PC Suite', 1, true, 42);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(78, 'IT102 PC Suite', 1, true, 42);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(79, 'IT106 PC Suite', 1, true, 67);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(80, 'IT125', 1, false, 122);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(81, 'IT125G', 1, false, 122);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(82, 'IT202', 1, false, 60);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(83, 'IT203', 1, false, 36);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(84, 'IT204', 1, false, 59);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(85, 'IT206', 1, false, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(86, 'IT207', 1, false, 33);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(87, 'IT250', 1, false, 244);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(88, 'MRA201 (MRI Theatre)', 7, false, 159);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(89, 'Áras Na Gaeilge PC Suite', 11, true, 16);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(90, 'Environmental Science PC Suite Room 209', 2, true, 13);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(91, 'Software Engineering PC Suite  Room 228/228A', 2, true, 40);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(92, 'Arts Faculty PC Suite Room 229/229A', 2, true, 35);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(93, 'Arts-Science PC Suite Room 105', 2, true, 45);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(94, 'Arts Millennium PC Suite Room 201', 3, true, 51);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(95, 'Block E PC Suite Room E102', 9, true, 39);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(96, 'Finnegan PC Suite', 9, true, 60);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(97, 'Cairnes PC Suite Room 112', 6, true, 38);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(98, 'MIME PC Suite', 12, true, 21);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(99, 'Clinical Science PC Suite', 12, true, 22);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(100, 'Clinical Science Library PC Suite', 12, true, 11);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(101, 'Education PC Suite Room D101', 13, true, 30);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(102, 'ENG2016 PC Suite', 4, true, 41);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(103, 'ENG2017 PC Suite', 4, true, 43);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(104, 'ENGG0046 PC Suite', 4, true, 80);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(105, 'Library 1st Floor PC Suite', 14, true, 20);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(106, 'Library 2nd Floor PC Suite', 14, true, 32);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(107, 'Library Special Collections PC Suite', 14, true, 6);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(108, 'Friary PC Suite Room 105', 15, true, 31);
INSERT INTO public.venues (venue_id, "name", building_id, is_lab, capacity) VALUES(109, 'Menlo PC Suite Room 102', 15, true, 19);

